# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8408d67b0740351aebe4332a6441cb48b0e83eb9ecbc2887569725145dfd0e5ed6734189da4d32e5f4009ee8de00686934c0af954667bbef5381ff676971376a

test:
  secret_key_base: 4e07f1a0b56bba3544c5c58ba523bee5782a13494dc0d518e2dda3f5fcd7ef7a6909d86f667344fbfad7710c440df48e85b63eabb08db9d42ec2db02b6cf22d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
